# Generated by Django 4.0.1 on 2022-02-12 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='variation_category',
            field=models.CharField(choices=[('Size', 'Size')], max_length=100),
        ),
    ]
