# Generated by Django 4.0.1 on 2022-02-12 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_variations_variation_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variations',
        ),
    ]
