# Generated by Django 4.0.1 on 2022-02-16 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_delete_sizes'),
        ('users', '0011_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='variation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.variations'),
        ),
    ]
