# Generated by Django 4.0.1 on 2022-02-21 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0011_alter_couponcode_code'),
        ('users', '0016_alter_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='variation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.variations'),
        ),
    ]
