# Generated by Django 4.0.1 on 2022-02-23 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_customer_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
