# Generated by Django 4.0.1 on 2022-02-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_couponcode_used_couponcode_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
    ]
