# Generated by Django 4.0.1 on 2022-02-12 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_remove_product_size'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sizes',
        ),
    ]
