# Generated by Django 4.0.1 on 2022-02-19 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_delete_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
